### ISSUE TITLE
extrapolation of Gridded interpolation is wrong

### ISSUE THREAD

**Issue by fp4code** [tlycken/Interpolations.jl#100] opened 2016-01-13 17:39 UTC
```julia
itp = interpolate(([0;10],),[100;110], Gridded(Linear()))
```
By the way, what is  REPL response [101.0 102.0] ?
```julia
etp = extrapolate(itp, Flat())
itp[5] # 105.0 OK
etp[5] # 102.0 Buggy
```
5 is considered as out of [1,2] interval (as documented but not as expected by common users)

**Comment by tlycken** [comment] 2016-01-13 18:05
Yeah, that's a bug.

The problem is that there are no method of `lbound` or `ubound` for gridded interpolants. We should definitely fix that, but you could define them in your workspace as a workaround (take a look at src/b-splines/b-splines.jl for inspiration).

Thanks for the report! If you'd like to file a PR that would be most appreciated :)

**Comment by tlycken** [comment] 2016-01-14 12:43
@fp4code If you do `Pkg.checkout("Interpolations"); Pkg.update()` in a Julia REPL now, this bug should be fixed. Do get back if you experience any problems! :)

**Closed** 2016-01-14 12:42 UTC
